// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhuQIXYRwx9FV1v8ACVoFvONtRRMkd_aU',
    appId: '1:797281644338:web:3f119c6dded4849e40b12b',
    messagingSenderId: '797281644338',
    projectId: 'budgettracker-6e604',
    authDomain: 'budgettracker-6e604.firebaseapp.com',
    storageBucket: 'budgettracker-6e604.firebasestorage.app',
    measurementId: 'G-BGCRQHQR4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1ODP9NXXcA_qBnQg6CIiF_Lz0fvBDDw',
    appId: '1:797281644338:android:f3674e71ca8017d940b12b',
    messagingSenderId: '797281644338',
    projectId: 'budgettracker-6e604',
    storageBucket: 'budgettracker-6e604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzggNDwChvUVWfRdxmHbylHzjdzmvi9R4',
    appId: '1:797281644338:ios:36a28cb5af8d677240b12b',
    messagingSenderId: '797281644338',
    projectId: 'budgettracker-6e604',
    storageBucket: 'budgettracker-6e604.firebasestorage.app',
    iosBundleId: 'com.example.firebasevaluta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzggNDwChvUVWfRdxmHbylHzjdzmvi9R4',
    appId: '1:797281644338:ios:36a28cb5af8d677240b12b',
    messagingSenderId: '797281644338',
    projectId: 'budgettracker-6e604',
    storageBucket: 'budgettracker-6e604.firebasestorage.app',
    iosBundleId: 'com.example.firebasevaluta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhuQIXYRwx9FV1v8ACVoFvONtRRMkd_aU',
    appId: '1:797281644338:web:be7be9616124cab040b12b',
    messagingSenderId: '797281644338',
    projectId: 'budgettracker-6e604',
    authDomain: 'budgettracker-6e604.firebaseapp.com',
    storageBucket: 'budgettracker-6e604.firebasestorage.app',
    measurementId: 'G-W98GZRQHKQ',
  );
}
